### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by MappingKat** [AtomLinter/linter-haml#32]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-haml](https://github.com/AtomLinter/linter-haml) package, v1.1.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at /Users/katrina/.atom/packages/linter-haml/lib/linter.coffee:151:28
    at Linter.lintFile (/Users/katrina/.atom/packages/linter-haml/lib/linter.coffee:138:14)
    at /Users/katrina/.atom/packages/linter-haml/lib/linter.coffee:122:26
```

### Commands

```
     -8:19.5.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -8:02.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:34.7.0 core:paste (atom-text-editor.editor.is-focused)
     -2:23.4.0 core:copy (atom-text-editor.editor.is-focused)
  2x -2:19.2.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:18.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:17.8.0 core:paste (atom-text-editor.editor.is-focused)
     -2:10.1.0 core:save (atom-text-editor.editor.is-focused)
     -2:03.6.0 core:save-as (atom-text-editor.editor.is-focused)
  3x -1:32.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:40.2.0 tree-view:move (span.name.icon.icon-file-text)
  4x -0:36.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:31.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "linter-haml": {
    "copyRubocopYml": true,
    "hamlLintExecutablePath": "/Users/katrina/.atom/packages/save-session/projects"
  }
}
```

### Installed Packages

```coffee
# User
autosave, v0.23.0
formatter-coffeescript, v0.1.1
language-haml, v0.23.15
linter, v1.11.3
linter-coffeescript, v1.0.0
linter-haml, v1.1.0
save-session, v0.15.7

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
It looks like you have specified your project director as the `hamlLintExecutablePath`, you need to update that to the full path to `haml-lint`, for example:

*   Windows: `where.exe haml-lint` -> `C:\Ruby22\bin\haml-lint.bat`
*   Linux: `which haml-lint` -> `/usr/local/bin/haml-lint`

**Comment by MappingKat** [comment]
ah.  ok thanks!  Paths and I don't get along...

**Comment by idoo** [comment]
Have the same issue, I've set my path is `~/.rbenv/shims/haml-lint` but it doesn't solve the issue in the atom 

Does anybody have some ideas?
